####PERIODO DE GARANTÍA

CÓMO HACER VÁLIDA MI GARANTÍA

Todos los productos que compras en la [Tienda de Xiaomi Colombia](/) tienen un periodo de garantía por defectos de fábrica, directamente con el fabricante a partir de la fecha de compra.

| Producto | Periodo de garantía |
| -- | -- |
| En todos los productos | [Periodo de garantía](/) |





Consulta el tiempo de garantía aquí

**Para hacer válida la garantía tome en cuenta la siguiente información:

1. Envía un correo a [hola@xiaomi-store.co](/) explicando el problema y/o falla que presenta el dispositivo. Necesitaremos su número de orden.

2. Una vez recibida la información se evaluará si efectivamente tu producto es válido para garantía. En caso de ser aprobada, te enviaremos un número de guía con el cual la mensajería pasará a tu domicilio por el producto. Te recomendamos empacar adecuadamente a fin de que no sufra daños durante el traslado.

3. Cuando recibamos el producto nos encargaremos de enviarlo a un taller autorizado para su evaluación técnica y en caso de ser necesario, se reparará con componentes autorizados (aplica para teléfonos celulares) o te lo cambiaremos por otro (aplica para el resto de los productos).

Una vez finalizado lo anterior, recibirás el producto en tu domicilio.
Nota: La póliza de garantía ampara todas las piezas y componentes del producto, incluye mano de obra y gastos de transportación que se deriven de su cumplimiento, sin costo adicional para ti, siempre y cuando presente un defecto de fábrica.

**La garantía no se hará efectiva en los siguientes casos:

1. Cuando el producto se hubiese utilizado en condiciones distintas a las normales.

2. Cuando el producto no hubiese sido operado de acuerdo con el instructivo de uso que se le acompaña.

3. Cuando el producto hubiese sido alterado o reparado por personas no autorizadas por el fabricante nacional, importador o comercializador responsable respectivo.

4. Cuando el producto presente algún daño causado por el usuario.
